package model;

public enum SessionStatus {
    WAITING_FOR_PLAYERS,
    WEREWOLF_KILL,
    BEGIN_SPECIAL_ROLES,
    PENDING_SPECIAL_ROLES,
    EXECUTION,
    PENDING_REPLAY,
    REPLAY,
    EXPIRED
}
